### ISSUE TITLE
add greenkeeper

### ISSUE THREAD

**Issue by lance** [nodeshift-starters/nodejs-circuit-breaker#11]
This should help to prevent failures based on security issues.

**Comment by lholmquist** [comment]
i'm not sure how easy this is going to be since there is no package.json at the root.

there is an open issue about it,  https://github.com/greenkeeperio/greenkeeper/issues/139

**Comment by lance** [comment]
Hmm - they are looking for contributors to implement this feature. I think you are right - it's not currently possible without a lot of chewing gum and baling wire.
