### ISSUE TITLE
Wrong return texts

### ISSUE THREAD

**Issue by mocenas** [nodeshift-starters/nodejs-circuit-breaker#36]
The booster should return text "Hello World!" but returns "Hello World" (missing exclamation mark).
Also the response should not contain an timestamp, which it does contain.
Same for fallback responses.

**Comment by helio-frota** [comment]
closing: https://github.com/bucharest-gold/nodejs-circuit-breaker/commit/7c0f21475cf918ac4f283a1c2e4648979006785d#diff-8a79f3967753d936ed3ca233d25aa959R43
