### ISSUE TITLE
Delay issue on CI

### ISSUE THREAD

**Issue by helio-frota** [nodeshift-starters/nodejs-circuit-breaker#40]
Sometimes we get this : 
` Error: expected 200 "OK", got 503 "Service Unavailable"`

**Comment by lance** [comment]
This happens when the pod has spun up but the service is not yet accepting requests.

**Comment by lance** [comment]
Please apply the BMSP™ /cc @bobmcwhirter

**Comment by lholmquist** [comment]
same thing happens with the basic rest booster.  i just hit the rebuild button on travis until it works
