### ISSUE TITLE
Runtime Failure on RHOAR GA

### ISSUE THREAD

**Issue by lance** [nodeshift-starters/nodejs-circuit-breaker#42]
When running the circuit breaker booster that is generated and downloaded as a zip file from https://launch.openshift.io the name service cannot be reached due to CORS.

> Failed to load http://nodejs-circuit-breaker-redhat-name-devnation.192.168.99.100.nip.io/api/info: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://nodejs-circuit-breaker-redhat-greeting-devnation.192.168.99.100.nip.io' is therefore not allowed access. The response had HTTP status code 503.

This is specifically when running in minishift. I have not tested deploying the resulting app to openshift online.

**Comment by lholmquist** [comment]
downloading now

**Comment by lholmquist** [comment]
ok, so i went to the launcher and did these steps

* chose zip flow
* chose circuit breaker
* chose Node.js
* downloaded the zip
* extracted zip
* ran `$ ./start-openshift.sh`

Working as expected

**Comment by lance** [comment]
Closing this. It only happens when I have two network interfaces active. Something's wrong with the NAT.
